// layerid-edge gRPC service definition.
//
// This is the public contract. Customers integrate against this; their SDKs
// generate stubs from this file. Treat it accordingly:
//   • additive changes only
//   • `reserved` field numbers for removals
//   • long deprecation windows for renames
//
// Mirror the same discipline as intel-service/proto/honeypot.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: edge.proto

package edgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                       // client IP (post-trusted-proxy unwrap)
	Ja3           string                 `protobuf:"bytes,2,opt,name=ja3,proto3" json:"ja3,omitempty"`                     // optional — empty if non-TLS
	Device        *DeviceSignals         `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`               // signals collected by the browser SDK
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // identifies the tenant
	Shadow        bool                   `protobuf:"varint,5,opt,name=shadow,proto3" json:"shadow,omitempty"`              // shadow-mode evaluation (no billing impact)
	ReqId         string                 `protobuf:"bytes,6,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`    // optional — caller can pre-allocate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ScoreRequest) GetJa3() string {
	if x != nil {
		return x.Ja3
	}
	return ""
}

func (x *ScoreRequest) GetDevice() *DeviceSignals {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *ScoreRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ScoreRequest) GetShadow() bool {
	if x != nil {
		return x.Shadow
	}
	return false
}

func (x *ScoreRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"` // required — one-time identifier
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *ConsumeRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`           // advisory — 0.0 to 1.0
	Verdict       string                 `protobuf:"bytes,3,opt,name=verdict,proto3" json:"verdict,omitempty"`         // suggestion — "allow" | "step-up" | "deny" | "log"
	Signals       *Signals               `protobuf:"bytes,4,opt,name=signals,proto3" json:"signals,omitempty"`         // the substantive payload
	Shadow        bool                   `protobuf:"varint,5,opt,name=shadow,proto3" json:"shadow,omitempty"`          // mirrors ScoreRequest.shadow
	Ts            int64                  `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`                  // server timestamp (unix seconds)
	Explanation   *Explanation           `protobuf:"bytes,7,opt,name=explanation,proto3" json:"explanation,omitempty"` // per-signal breakdown (dashboard/calibration)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreResponse) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *ScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ScoreResponse) GetSignals() *Signals {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *ScoreResponse) GetShadow() bool {
	if x != nil {
		return x.Shadow
	}
	return false
}

func (x *ScoreResponse) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ScoreResponse) GetExplanation() *Explanation {
	if x != nil {
		return x.Explanation
	}
	return nil
}

// Per-signal scoring breakdown — what fired, its weight, its contribution.
// Lets the dashboard show WHY a score is what it is. Opaque/ML scorers may
// leave it empty.
type SignalContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                   // e.g. "proxy_detection"
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`        // did this signal fire (else excluded)
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`               // [0,1] per-signal score
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`             // calibrated weight
	Contribution  float64                `protobuf:"fixed64,5,opt,name=contribution,proto3" json:"contribution,omitempty"` // score * weight
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`               // human-readable explanation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalContribution) Reset() {
	*x = SignalContribution{}
	mi := &file_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalContribution) ProtoMessage() {}

func (x *SignalContribution) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalContribution.ProtoReflect.Descriptor instead.
func (*SignalContribution) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{3}
}

func (x *SignalContribution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignalContribution) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *SignalContribution) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SignalContribution) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SignalContribution) GetContribution() float64 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

func (x *SignalContribution) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Explanation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*SignalContribution  `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"` // sum of contributions over available signals
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Explanation) Reset() {
	*x = Explanation{}
	mi := &file_edge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Explanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Explanation) ProtoMessage() {}

func (x *Explanation) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Explanation.ProtoReflect.Descriptor instead.
func (*Explanation) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{4}
}

func (x *Explanation) GetSignals() []*SignalContribution {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *Explanation) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_edge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                          // semver of this binary
	UpstreamOk    bool                   `protobuf:"varint,3,opt,name=upstream_ok,json=upstreamOk,proto3" json:"upstream_ok,omitempty"` // can we reach intel-service?
	CacheSize     int64                  `protobuf:"varint,4,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`    // entries in local intel cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_edge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUpstreamOk() bool {
	if x != nil {
		return x.UpstreamOk
	}
	return false
}

func (x *HealthResponse) GetCacheSize() int64 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

type DeviceSignals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canvas        string                 `protobuf:"bytes,1,opt,name=canvas,proto3" json:"canvas,omitempty"` // canvas fingerprint hash
	Webgl         string                 `protobuf:"bytes,2,opt,name=webgl,proto3" json:"webgl,omitempty"`   // WebGL renderer string
	Audio         string                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`   // AudioContext fingerprint
	Fonts         []string               `protobuf:"bytes,4,rep,name=fonts,proto3" json:"fonts,omitempty"`   // enumerated installed fonts
	Headless      bool                   `protobuf:"varint,5,opt,name=headless,proto3" json:"headless,omitempty"`
	Webdriver     bool                   `protobuf:"varint,6,opt,name=webdriver,proto3" json:"webdriver,omitempty"`
	UserAgentHash string                 `protobuf:"bytes,7,opt,name=user_agent_hash,json=userAgentHash,proto3" json:"user_agent_hash,omitempty"` // hashed, not raw — PII discipline
	Stun          *StunResult            `protobuf:"bytes,8,opt,name=stun,proto3" json:"stun,omitempty"`
	Timezone      string                 `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Locale        string                 `protobuf:"bytes,10,opt,name=locale,proto3" json:"locale,omitempty"`
	ScreenW       int32                  `protobuf:"varint,11,opt,name=screen_w,json=screenW,proto3" json:"screen_w,omitempty"`
	ScreenH       int32                  `protobuf:"varint,12,opt,name=screen_h,json=screenH,proto3" json:"screen_h,omitempty"`
	RttRatio      float64                `protobuf:"fixed64,13,opt,name=rtt_ratio,json=rttRatio,proto3" json:"rtt_ratio,omitempty"` // observed RTT vs geo-expected
	DeviceId      string                 `protobuf:"bytes,14,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`   // 64-bit derived identifier
	// Window + network-layer signals (added for the legacy scoring port).
	// Device-only — no raw-UA PII, no intel dependency. Optional; absent
	// fields leave their signal simply unavailable (drops out of the score).
	WindowW           int32  `protobuf:"varint,15,opt,name=window_w,json=windowW,proto3" json:"window_w,omitempty"`                                // window.innerWidth
	WindowH           int32  `protobuf:"varint,16,opt,name=window_h,json=windowH,proto3" json:"window_h,omitempty"`                                // window.innerHeight
	AppTimingMs       int32  `protobuf:"varint,17,opt,name=app_timing_ms,json=appTimingMs,proto3" json:"app_timing_ms,omitempty"`                  // max app-layer timing (ms), SDK-observed
	TcpRttMs          int32  `protobuf:"varint,18,opt,name=tcp_rtt_ms,json=tcpRttMs,proto3" json:"tcp_rtt_ms,omitempty"`                           // transport RTT (ms), edge/proxy capture
	BrowserReportedIp string `protobuf:"bytes,19,opt,name=browser_reported_ip,json=browserReportedIp,proto3" json:"browser_reported_ip,omitempty"` // JS-claimed public IP (vs transport peer IP)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceSignals) Reset() {
	*x = DeviceSignals{}
	mi := &file_edge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSignals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSignals) ProtoMessage() {}

func (x *DeviceSignals) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSignals.ProtoReflect.Descriptor instead.
func (*DeviceSignals) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceSignals) GetCanvas() string {
	if x != nil {
		return x.Canvas
	}
	return ""
}

func (x *DeviceSignals) GetWebgl() string {
	if x != nil {
		return x.Webgl
	}
	return ""
}

func (x *DeviceSignals) GetAudio() string {
	if x != nil {
		return x.Audio
	}
	return ""
}

func (x *DeviceSignals) GetFonts() []string {
	if x != nil {
		return x.Fonts
	}
	return nil
}

func (x *DeviceSignals) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *DeviceSignals) GetWebdriver() bool {
	if x != nil {
		return x.Webdriver
	}
	return false
}

func (x *DeviceSignals) GetUserAgentHash() string {
	if x != nil {
		return x.UserAgentHash
	}
	return ""
}

func (x *DeviceSignals) GetStun() *StunResult {
	if x != nil {
		return x.Stun
	}
	return nil
}

func (x *DeviceSignals) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *DeviceSignals) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *DeviceSignals) GetScreenW() int32 {
	if x != nil {
		return x.ScreenW
	}
	return 0
}

func (x *DeviceSignals) GetScreenH() int32 {
	if x != nil {
		return x.ScreenH
	}
	return 0
}

func (x *DeviceSignals) GetRttRatio() float64 {
	if x != nil {
		return x.RttRatio
	}
	return 0
}

func (x *DeviceSignals) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceSignals) GetWindowW() int32 {
	if x != nil {
		return x.WindowW
	}
	return 0
}

func (x *DeviceSignals) GetWindowH() int32 {
	if x != nil {
		return x.WindowH
	}
	return 0
}

func (x *DeviceSignals) GetAppTimingMs() int32 {
	if x != nil {
		return x.AppTimingMs
	}
	return 0
}

func (x *DeviceSignals) GetTcpRttMs() int32 {
	if x != nil {
		return x.TcpRttMs
	}
	return 0
}

func (x *DeviceSignals) GetBrowserReportedIp() string {
	if x != nil {
		return x.BrowserReportedIp
	}
	return ""
}

type StunResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Leaked         bool                   `protobuf:"varint,1,opt,name=leaked,proto3" json:"leaked,omitempty"`
	PublicIp       string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	LocalIp        string                 `protobuf:"bytes,3,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	WebrtcLocalIps []string               `protobuf:"bytes,4,rep,name=webrtc_local_ips,json=webrtcLocalIps,proto3" json:"webrtc_local_ips,omitempty"` // WebRTC host-candidate IPs (from JS)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StunResult) Reset() {
	*x = StunResult{}
	mi := &file_edge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StunResult) ProtoMessage() {}

func (x *StunResult) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StunResult.ProtoReflect.Descriptor instead.
func (*StunResult) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{8}
}

func (x *StunResult) GetLeaked() bool {
	if x != nil {
		return x.Leaked
	}
	return false
}

func (x *StunResult) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *StunResult) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *StunResult) GetWebrtcLocalIps() []string {
	if x != nil {
		return x.WebrtcLocalIps
	}
	return nil
}

type Signals struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Intel-derived (from intel-service/collector)
	Ja3Breadth       *Ja3Breadth       `protobuf:"bytes,1,opt,name=ja3_breadth,json=ja3Breadth,proto3" json:"ja3_breadth,omitempty"`
	ResidentialProxy *ResidentialProxy `protobuf:"bytes,2,opt,name=residential_proxy,json=residentialProxy,proto3" json:"residential_proxy,omitempty"`
	TcpFingerprint   string            `protobuf:"bytes,3,opt,name=tcp_fingerprint,json=tcpFingerprint,proto3" json:"tcp_fingerprint,omitempty"` // device class: "iot_cctv" | "android_tv" | "real_macos" | …
	DhtSightings     *DhtSightings     `protobuf:"bytes,4,opt,name=dht_sightings,json=dhtSightings,proto3" json:"dht_sightings,omitempty"`
	// Device-derived (from DeviceSignals, normalised)
	Headless      bool    `protobuf:"varint,10,opt,name=headless,proto3" json:"headless,omitempty"`
	Webdriver     bool    `protobuf:"varint,11,opt,name=webdriver,proto3" json:"webdriver,omitempty"`
	StunLeak      string  `protobuf:"bytes,12,opt,name=stun_leak,json=stunLeak,proto3" json:"stun_leak,omitempty"`
	RttRatio      float64 `protobuf:"fixed64,13,opt,name=rtt_ratio,json=rttRatio,proto3" json:"rtt_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signals) Reset() {
	*x = Signals{}
	mi := &file_edge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signals) ProtoMessage() {}

func (x *Signals) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signals.ProtoReflect.Descriptor instead.
func (*Signals) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{9}
}

func (x *Signals) GetJa3Breadth() *Ja3Breadth {
	if x != nil {
		return x.Ja3Breadth
	}
	return nil
}

func (x *Signals) GetResidentialProxy() *ResidentialProxy {
	if x != nil {
		return x.ResidentialProxy
	}
	return nil
}

func (x *Signals) GetTcpFingerprint() string {
	if x != nil {
		return x.TcpFingerprint
	}
	return ""
}

func (x *Signals) GetDhtSightings() *DhtSightings {
	if x != nil {
		return x.DhtSightings
	}
	return nil
}

func (x *Signals) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *Signals) GetWebdriver() bool {
	if x != nil {
		return x.Webdriver
	}
	return false
}

func (x *Signals) GetStunLeak() string {
	if x != nil {
		return x.StunLeak
	}
	return ""
}

func (x *Signals) GetRttRatio() float64 {
	if x != nil {
		return x.RttRatio
	}
	return 0
}

type Ja3Breadth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`                                    // "narrow" | "moderate" | "wide"
	SniCount      int32                  `protobuf:"varint,2,opt,name=sni_count,json=sniCount,proto3" json:"sni_count,omitempty"`             // distinct SNIs in last 7d
	TopSniShare   float64                `protobuf:"fixed64,3,opt,name=top_sni_share,json=topSniShare,proto3" json:"top_sni_share,omitempty"` // 0..1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ja3Breadth) Reset() {
	*x = Ja3Breadth{}
	mi := &file_edge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ja3Breadth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ja3Breadth) ProtoMessage() {}

func (x *Ja3Breadth) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ja3Breadth.ProtoReflect.Descriptor instead.
func (*Ja3Breadth) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{10}
}

func (x *Ja3Breadth) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Ja3Breadth) GetSniCount() int32 {
	if x != nil {
		return x.SniCount
	}
	return 0
}

func (x *Ja3Breadth) GetTopSniShare() float64 {
	if x != nil {
		return x.TopSniShare
	}
	return 0
}

type ResidentialProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeenIn        []string               `protobuf:"bytes,1,rep,name=seen_in,json=seenIn,proto3" json:"seen_in,omitempty"` // ["iproyal", "webshare", …]
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`     // 0..1
	LastSeenTs    int64                  `protobuf:"varint,3,opt,name=last_seen_ts,json=lastSeenTs,proto3" json:"last_seen_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResidentialProxy) Reset() {
	*x = ResidentialProxy{}
	mi := &file_edge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResidentialProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResidentialProxy) ProtoMessage() {}

func (x *ResidentialProxy) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResidentialProxy.ProtoReflect.Descriptor instead.
func (*ResidentialProxy) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{11}
}

func (x *ResidentialProxy) GetSeenIn() []string {
	if x != nil {
		return x.SeenIn
	}
	return nil
}

func (x *ResidentialProxy) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ResidentialProxy) GetLastSeenTs() int64 {
	if x != nil {
		return x.LastSeenTs
	}
	return 0
}

type DhtSightings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Categories    []string               `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"` // ["software-crack", "game", …]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DhtSightings) Reset() {
	*x = DhtSightings{}
	mi := &file_edge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DhtSightings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DhtSightings) ProtoMessage() {}

func (x *DhtSightings) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DhtSightings.ProtoReflect.Descriptor instead.
func (*DhtSightings) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{12}
}

func (x *DhtSightings) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DhtSightings) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_edge_proto protoreflect.FileDescriptor

const file_edge_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"edge.proto\x12\x0flayerid.edge.v1\"\xb0\x01\n" +
	"\fScoreRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03ja3\x18\x02 \x01(\tR\x03ja3\x126\n" +
	"\x06device\x18\x03 \x01(\v2\x1e.layerid.edge.v1.DeviceSignalsR\x06device\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x16\n" +
	"\x06shadow\x18\x05 \x01(\bR\x06shadow\x12\x15\n" +
	"\x06req_id\x18\x06 \x01(\tR\x05reqId\"@\n" +
	"\x0eConsumeRequest\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\xf2\x01\n" +
	"\rScoreResponse\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x18\n" +
	"\averdict\x18\x03 \x01(\tR\averdict\x122\n" +
	"\asignals\x18\x04 \x01(\v2\x18.layerid.edge.v1.SignalsR\asignals\x12\x16\n" +
	"\x06shadow\x18\x05 \x01(\bR\x06shadow\x12\x0e\n" +
	"\x02ts\x18\x06 \x01(\x03R\x02ts\x12>\n" +
	"\vexplanation\x18\a \x01(\v2\x1c.layerid.edge.v1.ExplanationR\vexplanation\"\xb0\x01\n" +
	"\x12SignalContribution\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x12\"\n" +
	"\fcontribution\x18\x05 \x01(\x01R\fcontribution\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\"b\n" +
	"\vExplanation\x12=\n" +
	"\asignals\x18\x01 \x03(\v2#.layerid.edge.v1.SignalContributionR\asignals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"\x0f\n" +
	"\rHealthRequest\"z\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vupstream_ok\x18\x03 \x01(\bR\n" +
	"upstreamOk\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x04 \x01(\x03R\tcacheSize\"\xce\x04\n" +
	"\rDeviceSignals\x12\x16\n" +
	"\x06canvas\x18\x01 \x01(\tR\x06canvas\x12\x14\n" +
	"\x05webgl\x18\x02 \x01(\tR\x05webgl\x12\x14\n" +
	"\x05audio\x18\x03 \x01(\tR\x05audio\x12\x14\n" +
	"\x05fonts\x18\x04 \x03(\tR\x05fonts\x12\x1a\n" +
	"\bheadless\x18\x05 \x01(\bR\bheadless\x12\x1c\n" +
	"\twebdriver\x18\x06 \x01(\bR\twebdriver\x12&\n" +
	"\x0fuser_agent_hash\x18\a \x01(\tR\ruserAgentHash\x12/\n" +
	"\x04stun\x18\b \x01(\v2\x1b.layerid.edge.v1.StunResultR\x04stun\x12\x1a\n" +
	"\btimezone\x18\t \x01(\tR\btimezone\x12\x16\n" +
	"\x06locale\x18\n" +
	" \x01(\tR\x06locale\x12\x19\n" +
	"\bscreen_w\x18\v \x01(\x05R\ascreenW\x12\x19\n" +
	"\bscreen_h\x18\f \x01(\x05R\ascreenH\x12\x1b\n" +
	"\trtt_ratio\x18\r \x01(\x01R\brttRatio\x12\x1b\n" +
	"\tdevice_id\x18\x0e \x01(\tR\bdeviceId\x12\x19\n" +
	"\bwindow_w\x18\x0f \x01(\x05R\awindowW\x12\x19\n" +
	"\bwindow_h\x18\x10 \x01(\x05R\awindowH\x12\"\n" +
	"\rapp_timing_ms\x18\x11 \x01(\x05R\vappTimingMs\x12\x1c\n" +
	"\n" +
	"tcp_rtt_ms\x18\x12 \x01(\x05R\btcpRttMs\x12.\n" +
	"\x13browser_reported_ip\x18\x13 \x01(\tR\x11browserReportedIpJ\x04\b\x14\x10 \"\x86\x01\n" +
	"\n" +
	"StunResult\x12\x16\n" +
	"\x06leaked\x18\x01 \x01(\bR\x06leaked\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12\x19\n" +
	"\blocal_ip\x18\x03 \x01(\tR\alocalIp\x12(\n" +
	"\x10webrtc_local_ips\x18\x04 \x03(\tR\x0ewebrtcLocalIps\"\x84\x03\n" +
	"\aSignals\x12<\n" +
	"\vja3_breadth\x18\x01 \x01(\v2\x1b.layerid.edge.v1.Ja3BreadthR\n" +
	"ja3Breadth\x12N\n" +
	"\x11residential_proxy\x18\x02 \x01(\v2!.layerid.edge.v1.ResidentialProxyR\x10residentialProxy\x12'\n" +
	"\x0ftcp_fingerprint\x18\x03 \x01(\tR\x0etcpFingerprint\x12B\n" +
	"\rdht_sightings\x18\x04 \x01(\v2\x1d.layerid.edge.v1.DhtSightingsR\fdhtSightings\x12\x1a\n" +
	"\bheadless\x18\n" +
	" \x01(\bR\bheadless\x12\x1c\n" +
	"\twebdriver\x18\v \x01(\bR\twebdriver\x12\x1b\n" +
	"\tstun_leak\x18\f \x01(\tR\bstunLeak\x12\x1b\n" +
	"\trtt_ratio\x18\r \x01(\x01R\brttRatioJ\x04\b\x05\x10\n" +
	"J\x04\b\x0e\x10\x14\"c\n" +
	"\n" +
	"Ja3Breadth\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1b\n" +
	"\tsni_count\x18\x02 \x01(\x05R\bsniCount\x12\"\n" +
	"\rtop_sni_share\x18\x03 \x01(\x01R\vtopSniShare\"m\n" +
	"\x10ResidentialProxy\x12\x17\n" +
	"\aseen_in\x18\x01 \x03(\tR\x06seenIn\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\flast_seen_ts\x18\x03 \x01(\x03R\n" +
	"lastSeenTs\"D\n" +
	"\fDhtSightings\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1e\n" +
	"\n" +
	"categories\x18\x02 \x03(\tR\n" +
	"categories2\xe5\x01\n" +
	"\x04Edge\x12F\n" +
	"\x05Score\x12\x1d.layerid.edge.v1.ScoreRequest\x1a\x1e.layerid.edge.v1.ScoreResponse\x12J\n" +
	"\aConsume\x12\x1f.layerid.edge.v1.ConsumeRequest\x1a\x1e.layerid.edge.v1.ScoreResponse\x12I\n" +
	"\x06Health\x12\x1e.layerid.edge.v1.HealthRequest\x1a\x1f.layerid.edge.v1.HealthResponseB.Z,github.com/layerid/edge/proto/edge/v1;edgev1b\x06proto3"

var (
	file_edge_proto_rawDescOnce sync.Once
	file_edge_proto_rawDescData []byte
)

func file_edge_proto_rawDescGZIP() []byte {
	file_edge_proto_rawDescOnce.Do(func() {
		file_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)))
	})
	return file_edge_proto_rawDescData
}

var file_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_edge_proto_goTypes = []any{
	(*ScoreRequest)(nil),       // 0: layerid.edge.v1.ScoreRequest
	(*ConsumeRequest)(nil),     // 1: layerid.edge.v1.ConsumeRequest
	(*ScoreResponse)(nil),      // 2: layerid.edge.v1.ScoreResponse
	(*SignalContribution)(nil), // 3: layerid.edge.v1.SignalContribution
	(*Explanation)(nil),        // 4: layerid.edge.v1.Explanation
	(*HealthRequest)(nil),      // 5: layerid.edge.v1.HealthRequest
	(*HealthResponse)(nil),     // 6: layerid.edge.v1.HealthResponse
	(*DeviceSignals)(nil),      // 7: layerid.edge.v1.DeviceSignals
	(*StunResult)(nil),         // 8: layerid.edge.v1.StunResult
	(*Signals)(nil),            // 9: layerid.edge.v1.Signals
	(*Ja3Breadth)(nil),         // 10: layerid.edge.v1.Ja3Breadth
	(*ResidentialProxy)(nil),   // 11: layerid.edge.v1.ResidentialProxy
	(*DhtSightings)(nil),       // 12: layerid.edge.v1.DhtSightings
}
var file_edge_proto_depIdxs = []int32{
	7,  // 0: layerid.edge.v1.ScoreRequest.device:type_name -> layerid.edge.v1.DeviceSignals
	9,  // 1: layerid.edge.v1.ScoreResponse.signals:type_name -> layerid.edge.v1.Signals
	4,  // 2: layerid.edge.v1.ScoreResponse.explanation:type_name -> layerid.edge.v1.Explanation
	3,  // 3: layerid.edge.v1.Explanation.signals:type_name -> layerid.edge.v1.SignalContribution
	8,  // 4: layerid.edge.v1.DeviceSignals.stun:type_name -> layerid.edge.v1.StunResult
	10, // 5: layerid.edge.v1.Signals.ja3_breadth:type_name -> layerid.edge.v1.Ja3Breadth
	11, // 6: layerid.edge.v1.Signals.residential_proxy:type_name -> layerid.edge.v1.ResidentialProxy
	12, // 7: layerid.edge.v1.Signals.dht_sightings:type_name -> layerid.edge.v1.DhtSightings
	0,  // 8: layerid.edge.v1.Edge.Score:input_type -> layerid.edge.v1.ScoreRequest
	1,  // 9: layerid.edge.v1.Edge.Consume:input_type -> layerid.edge.v1.ConsumeRequest
	5,  // 10: layerid.edge.v1.Edge.Health:input_type -> layerid.edge.v1.HealthRequest
	2,  // 11: layerid.edge.v1.Edge.Score:output_type -> layerid.edge.v1.ScoreResponse
	2,  // 12: layerid.edge.v1.Edge.Consume:output_type -> layerid.edge.v1.ScoreResponse
	6,  // 13: layerid.edge.v1.Edge.Health:output_type -> layerid.edge.v1.HealthResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_edge_proto_init() }
func file_edge_proto_init() {
	if File_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edge_proto_goTypes,
		DependencyIndexes: file_edge_proto_depIdxs,
		MessageInfos:      file_edge_proto_msgTypes,
	}.Build()
	File_edge_proto = out.File
	file_edge_proto_goTypes = nil
	file_edge_proto_depIdxs = nil
}
