// layerid-edge gRPC service definition.
//
// This is the public contract. Customers integrate against this; their SDKs
// generate stubs from this file. Treat it accordingly:
//   • additive changes only
//   • `reserved` field numbers for removals
//   • long deprecation windows for renames
//
// Mirror the same discipline as intel-service/proto/honeypot.proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: edge.proto

package edgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Edge_Score_FullMethodName   = "/layerid.edge.v1.Edge/Score"
	Edge_Consume_FullMethodName = "/layerid.edge.v1.Edge/Consume"
	Edge_Health_FullMethodName  = "/layerid.edge.v1.Edge/Health"
)

// EdgeClient is the client API for Edge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeClient interface {
	// Score a request. Idempotent — call as many times as needed.
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	// One-time race-safe consume of a req_id. Subsequent calls with the
	// same req_id return ALREADY_CONSUMED. Use this when the score must
	// not be replayable (login submit, checkout confirm).
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	// Health probe — used by K8s liveness / readiness.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type edgeClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeClient(cc grpc.ClientConnInterface) EdgeClient {
	return &edgeClient{cc}
}

func (c *edgeClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, Edge_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, Edge_Consume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Edge_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeServer is the server API for Edge service.
// All implementations must embed UnimplementedEdgeServer
// for forward compatibility.
type EdgeServer interface {
	// Score a request. Idempotent — call as many times as needed.
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	// One-time race-safe consume of a req_id. Subsequent calls with the
	// same req_id return ALREADY_CONSUMED. Use this when the score must
	// not be replayable (login submit, checkout confirm).
	Consume(context.Context, *ConsumeRequest) (*ScoreResponse, error)
	// Health probe — used by K8s liveness / readiness.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedEdgeServer()
}

// UnimplementedEdgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeServer struct{}

func (UnimplementedEdgeServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedEdgeServer) Consume(context.Context, *ConsumeRequest) (*ScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedEdgeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedEdgeServer) mustEmbedUnimplementedEdgeServer() {}
func (UnimplementedEdgeServer) testEmbeddedByValue()              {}

// UnsafeEdgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeServer will
// result in compilation errors.
type UnsafeEdgeServer interface {
	mustEmbedUnimplementedEdgeServer()
}

func RegisterEdgeServer(s grpc.ServiceRegistrar, srv EdgeServer) {
	// If the following call panics, it indicates UnimplementedEdgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Edge_ServiceDesc, srv)
}

func _Edge_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Edge_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edge_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Edge_Consume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).Consume(ctx, req.(*ConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edge_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Edge_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Edge_ServiceDesc is the grpc.ServiceDesc for Edge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Edge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "layerid.edge.v1.Edge",
	HandlerType: (*EdgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _Edge_Score_Handler,
		},
		{
			MethodName: "Consume",
			Handler:    _Edge_Consume_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Edge_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edge.proto",
}
